2022-02-17 13:41:20,780 ERROR: Exception on /login [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shivansh/shron/flaskblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shivansh/shron/flaskblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shivansh/shron/flaskblog/app/templates/login.html", line 8, in block 'content'
    {{ form.usernam.label }}<br>
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'usernam'
2022-02-17 13:41:20,980 ERROR: Exception on /login [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shivansh/shron/flaskblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shivansh/shron/flaskblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shivansh/shron/flaskblog/app/templates/login.html", line 8, in block 'content'
    {{ form.usernam.label }}<br>
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'usernam'
2022-02-17 13:41:56,475 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:48]
2022-02-19 14:25:46,662 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:48]
2022-02-19 14:26:19,514 ERROR: Exception on /reset_password_request [POST] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/home/shivansh/shron/flaskblog/app/email.py", line 17, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2022-02-19 14:37:40,125 ERROR: Exception on /reset_password_request [POST] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/home/shivansh/shron/flaskblog/app/email.py", line 17, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2022-02-19 14:41:22,609 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:48]
