2022-02-08 22:28:24,989 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-08 22:28:31,767 ERROR: Exception on /edit_profile [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 87, in edit_profile
    form = Edit_Profile_Form(current_user.username)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/shivansh/shron/flaskblog/app/forms.py", line 19, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
NameError: name 'EditProfileForm' is not defined
2022-02-08 22:30:59,096 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-09 16:08:40,444 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-09 16:08:51,567 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-10 12:24:21,177 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-10 15:16:41,006 INFO: Microblog startup [in /home/shivansh/shron/flaskblog/app/__init__.py:47]
2022-02-10 15:17:07,459 ERROR: Exception on /profile/shiv [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shivansh/shron/flaskblog/app/templates/user.html", line 28, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-02-10 15:20:02,700 ERROR: Exception on /profile/Shivansh [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shivansh/shron/flaskblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shivansh/shron/flaskblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shivansh/shron/flaskblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-02-10 15:21:05,915 ERROR: Exception on /profile/Shivansh [GET] [in /home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/shivansh/shron/flaskblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/shivansh/shron/flaskblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shivansh/shron/flaskblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/shivansh/shron/flaskblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/shivansh/shron/flaskblog/myenv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
